apply plugin: 'java'
apply from: rootProject.file('gradle/android-publish.gradle')
dependencies {

    compileOnly "com.android.tools.build:gradle:7.0.4"
    compileClasspath "com.android.tools.build:gradle:$android_tools_version"
    compileClasspath "com.google.guava:guava:$guava_version"
    implementation project(':lancet-base')
    implementation gradleApi()
//    compileOnly "com.google.guava:guava:24.1.1-jre"
    implementation("org.ow2.asm:asm:7.0")
    implementation("org.ow2.asm:asm-tree:7.0")
    implementation("org.ow2.asm:asm-util:7.0")
    implementation("org.ow2.asm:asm-commons:7.0")

}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"


