apply plugin: 'java'

dependencies {
    implementation project(":lancet-base")
    testImplementation project(":lancet-plugin")
    testImplementation project(":lancet-weaver")
    testImplementation gradleApi()
    testImplementation "com.android.tools.build:gradle:$android_tools_version"
//    testImplementation "junit:junit:4.12"
//    testImplementation 'com.squareup.okio:okio:1.11.0'
//    testImplementation 'org.assertj:assertj-core:3.6.2'
//    testImplementation 'org.mockito:mockito-core:2.8.47'

    testImplementation "junit:junit:4.13.2"
    testImplementation 'com.squareup.okio:okio:2.10.0'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testImplementation 'org.mockito:mockito-core:4.11.0'
    testImplementation 'org.mockito:mockito-inline:4.11.0'


    testImplementation("org.ow2.asm:asm:7.0")
    testImplementation("org.ow2.asm:asm-tree:7.0")
    testImplementation("org.ow2.asm:asm-util:7.0")
    testImplementation("org.ow2.asm:asm-commons:7.0")
}


task executeTestSample(type:JavaExec) {
    main = "com.sample.playground.Main"
    classpath = files('build/classes/java/main')
}

task executeTestSampleProduct(type:JavaExec) {
    main = "com.sample.playground.Main"
    classpath = files('build/product/java/main')
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"